export default [
  {
    _id: "RS101",
    name: "Rocket Propulsion",
    number: "RS4550",
    startDate: "2023-01-10",
    endDate: "2023-05-15",
    department: "D123",
    credits: 4,
    description: "This course provides an in-depth study of the fundamentals of rocket propulsion.",
    image: "/images/rocket.jpg",
  },
  {
    _id: "RS102",
    name: "Aerodynamics",
    number: "RS4560",
    startDate: "2023-01-10",
    endDate: "2023-05-15",
    department: "D123",
    credits: 3,
    description: "Comprehensive exploration of aerodynamics and fluid dynamics.",
    image: "/images/aerodynamics.jpg",
  },
  {
    _id: "RS103",
    name: "Spacecraft Design",
    number: "RS4570",
    startDate: "2023-01-10",
    endDate: "2023-05-15",
    department: "D123",
    credits: 4,
    description: "Principles and practices of spacecraft design and systems.",
    image: "/images/spacecraft.jpg",
  },
  {
    _id: "CS1234",
    name: "Organic Chemistry",
    number: "CH1230",
    startDate: "2023-01-10",
    endDate: "2023-05-15",
    department: "D134",
    credits: 3,
    description: "Study of carbon-based compounds and their properties.",
    image: "/images/chemistry1.jpg",
  },
  {
    _id: "CS1235",
    name: "Inorganic Chemistry",
    number: "CH1240",
    startDate: "2023-01-10",
    endDate: "2023-05-15",
    department: "D134",
    credits: 3,
    description: "Study of inorganic compounds and their behaviors.",
    image: "/images/chemistry2.jpg",
  },
  {
    _id: "CS1236",
    name: "Physical Chemistry",
    number: "CH1250",
    startDate: "2023-01-10",
    endDate: "2023-05-15",
    department: "D134",
    credits: 3,
    description: "Combines principles of physics and chemistry.",
    image: "/images/chemistry3.jpg",
  },
  {
    _id: "CS1237",
    name: "Ancient Languages",
    number: "HU1260",
    startDate: "2023-01-10",
    endDate: "2023-05-15",
    department: "D145",
    credits: 3,
    description: "Study of ancient Middle Eastern languages.",
    image: "/images/ancient.jpg",
  },
];